server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: department
    password: password
    
eureka:
  instance:
    client:
      serverUrl:
        defaultZone:  http://localhost:8761/eureka/

spring.boot.message: Hello, department message 123
