server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: department
    password: password
    
eureka:
  instance:
    client:
      serverUrl:
        defaultZone:  http://localhost:8761/eureka/
 
spring.boot.message: Hello, Employee message.
